version: '3.8'

services:
  admin-panel:
    container_name: zapal_react-app-dev
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile
    image: zapal/react-app:dev
    ports:
      - 3000:3000
    volumes:
      - /app/node_modules
      - .:/app
