version: '3.8'

services:
  admin-panel:
    container_name: zapal_react-app-prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: zapal/react-app:prod
    ports:
      - 8080:80
